### ISSUE TITLE
Mist output does not contain any contextual warnings

### ISSUE THREAD

**Issue by arawden** [AERO-ff/mist#1]
Given a sample failed output such as:

```
mist: evaporating Mistfile: /Users/nani/lab/anna/Mistfile
ninja: Entering directory `/Users/nani/lab/anna'
[1/1] lessc --clean-css "assets/css/anna.less" "pkg/assets/css/anna.min.css"
FAILED: lessc --clean-css "assets/css/anna.less" "pkg/assets/css/anna.min.css"
NameError: variable @headerGray is undefined in /Users/nani/lab/anna/assets/css/imports/clients.less on line 95, column 29:
94         tr:hover{
95           background-color: @headerGray;
96           .options{
ninja: build stopped: subcommand failed.
/Users/nani/lab/anna/assets/css/imports/4913 Created Removed OwnerModified IsFile
/Users/nani/lab/anna/assets/css/imports/clients.less Created Renamed Updated OwnerModified    AttributeModified IsFile
/Users/nani/lab/anna/assets/css/imports/clients.less~ Removed Renamed IsFile
```

There is no clear way to distinguish that a build has failed within the current implementation. I believe that determing when ninja builds fail and adding contextual colors would fix this.

**Comment by Qix-** [comment]
Waiting on #6.

**Comment by Qix-** [comment]
Well, #6 was to be able to render in order to see the _true_ behavior of Ninja. However, it demonstrated Ninja doesn't provide contextual colors either.

Will need to be a Ninja output processor stream. Not hard, just time consuming. Will implement in a little bit, probably after #9 and #17 (due to eliminated output routing based on platform).

**Comment by Qix-** [comment]
There are now contextual colors set up for certain parts of the system (mainly defects (uncaught errors) and syntax errors in your Mistfile).

Interestingly, this spawned another module, [node-backslash](http://github.com/Qix-/node-backslash). :)

**Comment by Qix-** [comment]
Marking this as closed. This is well and done at this point.
